accounts/urls.py
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns=[
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('update/<str:username>/', views.userupdate_view, name="userupdate"),
    path('<int:user_id>/follow/', views.follow_view, name='follow'),
    path('delete/', views.delete_view, name='delete'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'products'
urlpatterns = [
    path("", views.list_view, name="list"),
    path("create/", views.create_view, name="create"),
    path("<int:product_id>/", views.detail_view, name="detail"),
    path("<int:product_id>/update/", views.update_view, name="update"),
    path("<int:product_id>/delete/", views.delete_view, name="delete"),
    path("<int:product_id>/like/", views.like_view, name='like'),
    path("search/", views.search_view, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    following = models.ManyToManyField('self', related_name='followers', symmetrical=False)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email', 'image',)

class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = get_user_model()
        fields = ('email', 'image',)

class CustomPasswordChangeForm(PasswordChangeForm):
    pass

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from accounts.forms import CustomUserCreationForm, CustomUserChangeForm, CustomPasswordChangeForm
from django.shortcuts import get_object_or_404
from accounts.models import User
from django.contrib.auth.decorators import login_required
from products.models import Product
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash

# Create your views here.
def login_view(request):
    if request.method=="POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('products:list')
    return render(request, 'accounts/login.html')

@login_required
def logout_view(request):
    if request.method == "POST":
        logout(request)
    return redirect('products:list')

def signup_view(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            if User.objects.filter(email=email).exists():
                messages.error(request, "사용 중인 email입니다.")
                return render(request, 'accounts/signup.html', {"form":form})
            user = form.save()
            login(request, user)
            return redirect('products:list')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {"form":form})

@login_required
def userupdate_view(request, username):
    user = get_object_or_404(User, username=username)
    referer_url = request.META.get('HTTP_REFERER')
    if user != request.user:
        messages.warning(request, message='권한이 없습니다.')
        return redirect(referer_url or 'products:list')
    if request.method == 'POST':
        user_form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        password_form = CustomPasswordChangeForm(request.user, request.POST)
        context = {
            'user_form':user_form,
            'password_form':password_form
        }
        if user_form.is_valid() and password_form.is_valid():
            email = user_form.cleaned_data.get('email')
            if email != user.email and User.objects.filter(email=email).exists():
                messages.error(request, "사용 중인 email입니다.")
                return render(request, 'accounts/user_update.html', context)
            old_password = password_form.cleaned_data.get('old_password')
            new_password1 = password_form.cleaned_data.get('new_password1')
            if old_password == new_password1:
                messages.error(request, '새 비밀번호는 기존 비밀번호와 달라야 합니다.')
                return render(request, 'accounts/user_update.html', context)
            user_form.save()
            password_form.save()
            update_session_auth_hash(request, password_form.user)
            messages.success(request, '비밀번호가 변경되었습니다.')
            return redirect('products:list')
    else:
        user_form = CustomUserChangeForm(instance=request.user)
        password_form = CustomPasswordChangeForm(request.user)
        context = {
            'user_form': user_form,
            'password_form': password_form
        }
    return render(request, 'accounts/user_update.html', context)

def profile_view(request, username):
    user = get_object_or_404(User, username=username)
    products = Product.objects.filter(author=user.id)
    like_products = Product.objects.filter(like_user=user.id)
    context = {
        'user': user,
        'products': products,
        'like_products':like_products
    }
    return render(request, 'accounts/profile.html', context)

def follow_view(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if member != request.user:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("accounts:profile", username=member.username)

@login_required
def delete_view(request):
    if request.method == 'POST':
        Product.objects.filter(author=request.user).delete()
        Product.objects.filter(like_user=request.user).delete()
        User.objects.filter(followers=request.user).delete()
        User.objects.filter(following=request.user).delete()
        request.user.delete()
        logout(request)
        messages.success(request, '계정이 성공적으로 삭제되었습니다.')
        return redirect('products:list')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1> 로그인 </h1>
<form action="" method="POST">
    {% csrf_token%}
    <input type="text" name="username">
    <input type="password" name="password">
    <button type="submit">로그인</button>
</form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.image %}
    <img src="{{ user.image.url }}" alt="{{ user.username }}">
{% else %}
    <img src="{% static 'images/user.png' %}" alt="">
{% endif %}
<h1> username: {{ user.username }}</h1>
<p> {{ user.created_at }}</p>
<form action="{% url 'accounts:userupdate' user.username %}", method="">
    {% csrf_token %}
    <button>유저 수정</button>
</form>
<p> 현재 팔로워 {{ user.followers.count }}명</p>
<p> 현재 팔로잉 {{ user.following.count }}명</p>
<form action="{% url 'accounts:follow' user.pk %}", method="POST">
    {% csrf_token %}
    {% if request.user in user.followers.all %}
    <button> 팔로우 취소 </button>
    {% else %}
    <button>팔로우</button>
    {% endif %}
</form>
작성글
<ul>
    {% for product in products %}
    <li>
        <a href="{% url 'products:detail' product.id %}">
        <div>{{ product.title }}</div>
        <div>{{ product.content }}</div>
        <div>{{ product.price }}</div>
        <div>{{ product.author }}</div>
        <form action="{% url 'products:like' product.id %}" method="POST">
            {% csrf_token %}
            {% if request.user in product.like_user.all %}
            <button> 좋아요 취소 </button>
            {% else %}
            <button>좋아요</button>
            {% endif %}
        </form>
        </a>
    </li>
    {% endfor %}
    </ul>
좋아요누른글
{% for product in like_products %}
    <li>
        <a href="{% url 'products:detail' product.id %}">
        <div>{{ product.title }}</div>
        <div>{{ product.content }}</div>
        <div>{{ product.price }}</div>
        <div>{{ product.author }}</div>
        <form action="{% url 'products:like' product.id %}" method="POST">
            {% csrf_token %}
            {% if request.user in product.like_user.all %}
            <button> 좋아요 취소 </button>
            {% else %}
            <button>좋아요</button>
            {% endif %}
        </form>
    
        </a>
    </li>
    {% endfor %}

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>회원가입</h1>
    <form action="{% url 'accounts:signup' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">회원가입</button>
    </form>
{% endblock %}

accounts/templates/accounts/user_update.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST", enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ password_form.as_p }}
        <button type="submit">완료</button>
    </form>
{% endblock %}