accounts/urls.py
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns=[
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('update/<str:username>/', views.userupdate_view, name="userupdate"),
    path('<int:user_id>/follow/', views.follow_view, name='follow'),
    path('delete/', views.delete_view, name='delete'),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'products'
urlpatterns = [
    path("", views.list_view, name="list"),
    path("create/", views.create_view, name="create"),
    path("<int:product_id>/", views.detail_view, name="detail"),
    path("<int:product_id>/update/", views.update_view, name="update"),
    path("<int:product_id>/delete/", views.delete_view, name="delete"),
    path("<int:product_id>/like/", views.like_view, name='like'),
    path("search/", views.search_view, name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spartamarket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav>
        <a href="{% url 'products:list' %}"><button>청순 수연</button></a>
        <form action="{% url 'products:search' %}" method="GET">
        <input type="text", name='keyword'>
        <button>search</button>
        </form>
        {% if request.user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="logout">
        </form>
        <a href="{% url 'products:create' %}">새 글 작성</a>
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="delete">
        </form>
        <a href="{% url 'accounts:profile' request.user.username %}">내 프로필</a>
        {% else %}
            <a href="{% url 'accounts:login' %}">login</a>
            <a href="{% url 'accounts:signup' %}">signup</a>
        {% endif %}
    </nav>
    {% for message in messages %}
    <li> {{ message }} </li>
    {% endfor %}

    {% block content %}
    {% endblock content %}
</body>
</html>